module.exports = {
  projects: [
    '<rootDir>/apps/ngx-bootstrap-docs',
    '<rootDir>/libs/utils',
    '<rootDir>/libs/positioning',
    '<rootDir>/libs/component-loader',
    '<rootDir>/libs/chronos',
    '<rootDir>/libs/locale',
    '<rootDir>/libs/mini-ngrx',
    '<rootDir>/libs/accordion',
    '<rootDir>/libs/alert',
    '<rootDir>/libs/dropdown',
    '<rootDir>/libs/modal',
    '<rootDir>/libs/collapse',
    '<rootDir>/libs/progressbar',
    '<rootDir>/libs/tabs',
    '<rootDir>/libs/buttons',
    '<rootDir>/libs/pagination',
    '<rootDir>/libs/rating',
    '<rootDir>/libs/timepicker',
    '<rootDir>/libs/carousel',
    '<rootDir>/libs/datepicker',
    '<rootDir>/libs/popover',
    '<rootDir>/libs/sortable',
    '<rootDir>/libs/tooltip',
    '<rootDir>/libs/typeahead',
  ],
};
